[versions]
compose = "1.8.1"
junit = "4.13.2"
kotlin = "2.1.21"
koin = "4.0.3"
file-picker = "3.1.0"
gson = "2.11.0"
kmd2pdf = "0.2.2"
collection = "1.4.0"
coroutines = "1.10.2"
native-file-chooser = "1.6.4"
viewmodel-compose = "2.9.0"

[libraries]
karkdown-core-ui = { module = "com.github.enteraname74.karkdowncoreui:karkdown-core-ui", version = "" }

file-picker = { module = "com.darkrockstudios:mpfilepicker", version.ref = "file-picker" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
kmd2pdf = {  module = "com.github.woojiahao:kMD2PDF", version.ref = "kmd2pdf" }
native-file-chooser = { module = "li.flor:native-j-file-chooser", version.ref = "native-file-chooser" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }


androidx-collection = { module = "androidx.collection:collection", version.ref = "collection" }

viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "viewmodel-compose"}

[plugins]
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }